
FROM nginx:alpine


COPY ./index.html /usr/share/nginx/html/index.html
COPY ./style.css /usr/share/nginx/html/style.css
COPY ./imagenes/informatica.jpg /usr/share/nginx/html/imagenes/informatica.jpg
